baseurl = "/"
Paginate = 5

[params]
  env = "production"
  enableRobotsTXT = true

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
  
# datocms:start
title = "Vivienne Must & other stories "
languageCode = "en"
# datocms:end