baseurl = "/"
Paginate = 5

[params]
  env = "development"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

enableRobotsTXT = true

# datocms:start
title = "Vivienne Must & other stories"
languageCode = "en"
# datocms:end