baseurl = "/"
Paginate = 5
enableRobotsTXT = true


[params]
  env = "development"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

# datocms:start
title = "Vivienne Must & other stories "
languageCode = "en-AU"
# datocms:end