baseurl = "/"
Paginate = 5

[params]
  env = "development"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# datocms:start
title = "Creative Inc."
languageCode = "en"
# datocms:end